### ISSUE TITLE
After updating to Xcode 9.3 and Swift 4.1 Float is not able to map the values

### ISSUE THREAD

**Issue by krishnameena** [Hearst-DD/ObjectMapper#954]
I just updated to Xcode 9.3 and Swift 4.1 and  Float is not able to map the values, but when I changed Float to CGFloat it is working fine.

It is giving lots of compilation warnings also. PFA attached screenshot of warnings.

<img width="247" alt="screen shot 2018-03-31 at 12 53 09 pm" src="https://user-images.githubusercontent.com/10487399/38160912-8e56b140-34e2-11e8-9725-205d4a3ecf85.png">

**Comment by marioyohanes** [comment]
I got same issue on Swift 4.1 + Xcode 9.3. My workaround atm is to update our transformer to cast the object to `NSNumber` and get the `.floatValue`. There will be rounding issue, but it's not a problem at least for my project.

**Comment by AmirDaliri** [comment]
Does anyone have solution?

**Comment by mylemans** [comment]
We're worried about these warnings: so far everything looks like its working, but since we use it to transfer data to a backend we do not manage, it is very hard for us to confirm everything still works as it used to. Any idea when the warnings will be fixed?

**Comment by sandeepo2o** [comment]
I am facing the same issue.
so I installed 9.2 with swift 4.0. Now it is working charmingly.
We have to use 9.2 and swift 4.0. I didn't try Xcode 9.3 + Swift 4.0.

**Comment by Codeido** [comment]
Same problems here

**Comment by quetool** [comment]
@sandeepo2o the problem is you need Xcode 9.3 with iOS 11.3 and many of us updated to iOS 11.3

**Comment by quetool** [comment]
I have similar issue here https://github.com/Hearst-DD/ObjectMapper/issues/955

**Comment by EduardoViegas** [comment]
I have the same problem.
The workaround that worked for me and had less impact was to use a Custom Transform:

```swift
class CustomFloatTransform: TransformType {
    public typealias Object = Float
    public typealias JSON = NSNumber
    
    func transformFromJSON(_ value: Any?) -> Float? {
        if let number = value as? NSNumber {
            return number.floatValue
        }
        
        if let numberString = value as? String {
            return Float(numberString)
        }
        
        return nil
    }
    
    func transformToJSON(_ value: Float?) -> NSNumber? {
        if let float = value {
            return NSNumber(value: float)
        }
        return nil
    }
}
```

**Comment by cordechasse** [comment]
I've got the same issue on my projet.
@EduardoViegas's workaround works well until the bug is fixed.

**Comment by TimchenKKBOX** [comment]
Same Problem here

**Comment by scott4arrows** [comment]
we just changed Floats to Double in our models

**Comment by leojkwan** [comment]
Does anyone have any information as to whether this is a bug or a legitimate API change with NSNumber and Floats in Swift 4.1?

**Comment by XiaoChenYung** [comment]
i have same trouble, hope this can be solved as soon as possible.

**Comment by itruf** [comment]
Same trouble, I converted all floats to doubles

**Comment by tristanhimmelman** [comment]
@pmusolino sorry no updates on this. I don't have time to dig into this issue at the moment.

**Comment by tristanhimmelman** [comment]
Hi all, I have merged a PR which should address the Float issue. Please use version 3.2.0.

I have not had a chance to look at the redeclaration warnings yet.

**Comment by tristanhimmelman** [comment]
Closing this ticket as it is a duplicate of #967

**Comment by xenon-15** [comment]
It is strange that we are still facing the float mapping issue using XCode 9.4.1 and Swift 4.1 and both v3.2.0 and v 3.3.0 of ObjectMapper.
 
Following is the code :

`struct Quote {
    fileprivate(set) var choices: [UpgradeSlot] = []
    fileprivate(set) var uuid: String!
    fileprivate(set) var dateCreated: String?
    fileprivate(set) var signature: String!
}

extension Quote: ValidatedMappable {
    static var requiredKeys: [String] = [ "userUuid", "signature" ]

    mutating func mapping(map: Map) {
        choices <- map["choices"]
        uuid <- map["userUuid"]
        dateCreated <- map["createdAt"]
        signature <- map["signature"]
    }
}

struct UpgradeSlot: Equatable {

    fileprivate(set) var price: Price!
    fileprivate(set) var discount: Float?
    fileprivate(set) var amount: Int!
    fileprivate(set) var term: Int!
    fileprivate(set) var discountValue: Float?
    fileprivate(set) var discountType: DiscountType?
    fileprivate(set) var schemeIncentive: String?
    fileprivate(set) var taxes: Float?
    fileprivate(set) var taxesAmount: Float?
    fileprivate(set) var message: String?
    fileprivate(set) var type: String?
    fileprivate(set) var durationUnit: DurationUnit?
    fileprivate(set) var discountExpiresOn: Date?
    fileprivate(set) var popularDisplayScheme: Bool?
    fileprivate(set) var discountedPricePerMonth: Price?
}

extension UpgradeSlot: ValidatedMappable {
    static var requiredKeys: [String] = [ JSONKeys.price, JSONKeys.amount, JSONKeys.term ]

    mutating func mapping(map: Map) {
        discountType <- (map[JSONKeys.discountType], EnumTransform())
        discountValue <- map[JSONKeys.discountValue]
        schemeIncentive <- map[JSONKeys.schemeIncentive]
        type <- map[JSONKeys.type]
        price <- map[JSONKeys.price]
        discount <- map[JSONKeys.discountedPrice]
        amount  <- map[JSONKeys.amount]
        taxes <- map[JSONKeys.tax]
        taxesAmount <- map[JSONKeys.taxAmount]
        term <- map[JSONKeys.term]
        durationUnit <- (map[JSONKeys.durationUnit], EnumTransform())
        message <- map[JSONKeys.message]
        discountExpiresOn <- (map[JSONKeys.discountExpiresOn], UTCDateFormatterTransform(formatString: "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'sss'Z'"))
        popularDisplayScheme <- map[JSONKeys.popularDisplayScheme]
        discountedPricePerMonth <- map[JSONKeys.discountedPricePerMonth]
    }
    
    fileprivate enum JSONKeys {
        static let price = "originalPrice"
        static let amount = "slots"
        static let term = "tenure.duration"
        static let discountType = "discount.type"
        static let discountValue = "discount.value"
        static let schemeIncentive = "schemeIncentive"
        static let type = "type"
        static let discountedPrice = "discountedPrice"
        static let tax = "tax"
        static let taxAmount = "taxAmount"
        static let durationUnit = "tenure.durationUnit"
        static let message = "description"
        static let discountExpiresOn = "discountExpiresOn"
        static let popularDisplayScheme = "popularDisplayScheme"
        static let discountedPricePerMonth = "discountedPricePerMonth"
    }
}

func == (lhs: UpgradeSlot, rhs: UpgradeSlot) -> Bool {
    return lhs.amount == rhs.amount && lhs.term == rhs.term
}
`

Sample response from the REST endpoint:
`"quote": {
    "choices": [
      {
        "type": "prepaid-slot",
        "originalPrice": 15.2,
        "discountedPrice": 11.45,
        "schemeIncentive": "Transactional",
        "description": null,
        "tax": 6.25,
        "taxAmount": 0.72,
        "discount": {
          "value": 3.75,
          "type": "DOLLARS"
        },
        "discountExpiresOn": "2019-12-31T00:00:00.000Z",
        "slots": 2,
        "tenure": {
          "duration": 2,
          "durationUnit": "MONTHS"
        },
        "popularDisplayScheme": true,
        "originalPricePerMonth": 7.6,
        "discountedPricePerMonth": 5.73,
        "slotStartDate": "2018-08-21T17:49:15.335Z",
        "slotEndDate": "2018-10-21T17:49:15.335Z"
      },
      {
        "type": "prepaid-slot",
        "originalPrice": 15,
        "discountedPrice": 12,
        "schemeIncentive": "Traxsactional",
        "description": null,
        "tax": 6.25,
        "taxAmount": 0.75,
        "discount": {
          "value": 3,
          "type": "T1"
        },
        "discountExpiresOn": null,
        "slots": 1,
        "tenure": {
          "duration": 12,
          "durationUnit": "MONTHS"
        },
        "popularDisplayScheme": false,
        "originalPricePerMonth": 1.25,
        "discountedPricePerMonth": 1,
        "slotStartDate": "2018-08-21T17:49:15.342Z",
        "slotEndDate": "2019-08-21T17:49:15.342Z"
      }
    ],
    "userUuid": "f7bf2860-2916-37c5-95eb-7f0ca4d3ac39",
    "createdAt": "2018-08-21T17:49:15.348Z",
    "signature": "bxxxxxdd0212378649284cb123e4656b9xxxxxxa202b828"
  }`

We are getting the error in mapping of **first** item in the **choices** array while the second one is mapped correctly.

`taxesAmount	Float!	0.720000029` instead of 0.72
`price	Price!	15.1999998` instead of 15.2
`discount	Price?	11.4499998` instead of 11.45


Is there something we are doing wrong?
